{{- if .Values.rabbit.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbit.credentialsSecret }}
type: Opaque
stringData:
  username: {{ .Values.rabbit.username | quote }}
  password: {{ .Values.rabbit.password | quote }}
{{- end }}
{{- if and .Values.rabbit.createSecret .Values.registry.createSecret }}
---
{{- end }}
{{- if .Values.registry.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.credentialsSecret }}
type: Opaque
stringData:
  username: {{ .Values.registry.username | quote }}
  password: {{ .Values.registry.password | quote }}
{{- end }}
