# application.yml

crawler:
  crawl:
    namespace: @crawler.crawl.namespace@
    server:
      zk: @crawler.crawl.server.zk@
      retryAttempts: @crawler.crawl.server.retryAttempts@
      retryDelayMs: @crawler.crawl.server.retryDelayMs@
    threadCount: @crawler.crawl.threadCount@

  registry:
    ws:
      url: @crawler.registry.ws.url@

  mq:
    host: @crawler.mq.host@
    virtualHost: @crawler.mq.virtualHost@
    username: @crawler.mq.username@
    password: @crawler.mq.virtualHost@



